//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Circuit
{
	public virtual List<Gate> gates
	{
		get;
		set;
	}

	public virtual List<Sink> sinks
	{
		get;
		set;
	}

	public virtual List<Source> sources
	{
		get;
		set;
	}

	public virtual void DrawAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DrawConnections()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveElement()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveElement()
	{
		throw new System.NotImplementedException();
	}

}

