//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Circuit
{
	public static List<Element> elements
	{
		get;
		set;
	}

	public virtual List<Sink> sinks
	{
		get;
		set;
	}

	public virtual Element Element
	{
		get;
		set;
	}

	public virtual Sink Sink
	{
		get;
		set;
	}

	public virtual void DrawAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DrawSinksAndConnections()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MoveElement(object Element el, object int toX, object int toY)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveElement(object Element el)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddElement(object EnumElementType type)
	{
		throw new System.NotImplementedException();
	}

	public virtual Element FindElement(object int X, object int Y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FindConnectionPoint(object int X, object int Y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void MakeConnection(object connectionPoint A, object connectionPoint Z)
	{
		throw new System.NotImplementedException();
	}

}

