//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class ConnectionPoint
{
	public virtual int X
	{
		get;
		set;
	}

	public virtual int Y
	{
		get;
		set;
	}

	public virtual int Radius
	{
		get;
		set;
	}

	public virtual bool AreYouClicked()
	{
		throw new System.NotImplementedException();
	}

}

