//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Form
{
	public virtual Circuit curCircuit
	{
		get;
		set;
	}

	public virtual Circuit Circuit
	{
		get;
		set;
	}

	public virtual void Save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Load()
	{
		throw new System.NotImplementedException();
	}

	public virtual void New()
	{
		throw new System.NotImplementedException();
	}

}

