//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Gate : Element
{
	public virtual InputPoint input[2]
	{
		get;
		set;
	}

	public virtual OutputPoint output
	{
		get;
		set;
	}

	public virtual InputPoint InputPoint
	{
		get;
		set;
	}

	public virtual OutputPoint OutputPoint
	{
		get;
		set;
	}

	public virtual int calculateOutput()
	{
		throw new System.NotImplementedException();
	}

}

