//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sink : Element
{
	public virtual InputPoint input
	{
		get;
		set;
	}

	public static Image[2] IMG
	{
		get;
		set;
	}

	public virtual InputPoint InputPoint
	{
		get;
		set;
	}

}

