//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Source : Element
{
	public virtual bool state
	{
		get;
		set;
	}

	public virtual Element outputTo
	{
		get;
		set;
	}

}

